name = "auto-run-ac-api"
main = "src/worker.ts"
compatibility_date = "2023-08-21"
node_compat = true

[[d1_databases]]
binding = "TRIGGERS"
database_name = "triggers"
database_id = "27e105c8-8221-45da-8ffb-4bb0f227ea89"
migrations_dir = "src/db/migrations"
