name: setup-node
description: Setup Node.js and pnpm with Volta
runs:
  using: composite
  steps:
    - name: Launch Turbo Remote Cache Server
      uses: dtinth/setup-github-actions-caching-for-turbo@v1.1.0
    - name: Get node version from Volta
      id: get-node-version
      uses: keita-hino/get-node-version-from-volta@main
    - name: Install pnpm
      uses: pnpm/action-setup@v2
    - name: Get node version from Volta
      id: get-node-version
      uses: keita-hino/get-node-version-from-volta@main
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
        cache: pnpm
    - name: Install dependencies
      run: pnpm i
      shell: bash
