name = "auto-run-ac"
main = "src/worker.ts"
compatibility_date = "2023-08-01"
compatibility_flags = ["nodejs_compat"]
# アカウントIDはシークレットな値ではない
account_id = "fff06038a70892193e0fa1e9e270436a"
kv_namespaces = [
  { binding = "HISTORY", id = "2622aa221d65472ca1b9595c31a388cf", preview_id = "d39881391df24b1891c808b74d9b4937" }
]

[vars]
NODE_ENV = "production"
METER_DEVICE_ID = "DC49091D8404"
AIR_CONDITIONER_DEVICE_ID = "02-202306140644-28427602"
SENTRY_DSN = "https://a806b31ea1f54f39ac1f7526d1c20e98@sentry.celesteria.net/2"

[env.development]
kv_namespaces = [
  { binding = "HISTORY", id = "2622aa221d65472ca1b9595c31a388cf", preview_id = "d39881391df24b1891c808b74d9b4937" },
]

[env.development.vars]
NODE_ENV = "development"
METER_DEVICE_ID = "DC49091D8404"
AIR_CONDITIONER_DEVICE_ID = "02-202306140644-28427602"
SENTRY_DSN = "https://a806b31ea1f54f39ac1f7526d1c20e98@sentry.celesteria.net/2"

[triggers]
# 15分ごとに実行する
crons = ["*/15 * * * *"]

services = [
  { binding = "AUTO_RUN_AC_API", service = "auto-run-ac-api" }
]
